### ISSUE TITLE
Magic Earth with A11 shows "No new Messages..."

### ISSUE THREAD

**Issue by nexx512** [sn-00-x/aa4mg#16]
Thank you for this great piece of software to make AA workig with lineage + MicroG.

I have LineageOS 18 with MicroG running. Installation worked great and I can see Magic Earth as Navi app. But when I start Magic Earth I only see the message "No New messages on this trip" (in German... So i don't know the exact english message).
![IMG_20230818_191431](https://github.com/sn-00-x/aa4mg/assets/24672655/40154f6b-0088-405f-825b-57bcbbe321f8)

It works on a phone with GAPPs installed so I expect that it has to do with the stub.

Unfortunately I don't know how to provide more useful Information.

**Comment by 30nE** [comment]
I have the same problem on a LOS 20 with MicroG on Pixel-7.

**Comment by tomechio** [comment]
I had the sama issue and I managed to get the Magic Earth work correctly when I connected my phone to my PC and AA emulator of the Android Studio. After that I installed AA AIO tweaker, selected all apps to be active in AA and since then ME has worked correctly in my car.

**Comment by nexx512** [comment]
I tried this but for me it didn't work unfortunately. Same behaviour as before.

**Comment by nexx512** [comment]
It works now. Thanks a lot for your hint. I missed out the AA emulator (called [Desktop Head Unit](https://developer.android.com/training/cars/testing/dhu)) part at first. Funny that you first have to connect it once to the AA emulator and then it works in the car.

Not sure if that can be closed now or if there are some adaptions required in this project.

**Comment by nexx512** [comment]
OK, after rebooting my phone, it didn't work anymore. So every time I want to use Magic Earth, I first have to connect it to the AA emulator on my notebook. This is a bit of a pain.
I don't know what's different between the AA emulator and a real car and how this error can be fixed.
Any ideas welcome.

**Comment by mrestivill** [comment]
I've tried to install LSPosed following the README.md documentation and activate LSPosed android auto extension selecting Magic Earth application and it works.

**Comment by tomechio** [comment]
I found out that this is actually not a aa4mg related issue. As stated in Magic Earth's webpage, there are issues if the app is not istalled from the play store. 
[install Magic Earth from Google play. APKs from other sources may not work with Android Auto.](https://www.magicearth.com/faq-en/)

I managed to get it work by activating [Shizuku](https://shizuku.rikka.app/) on my phone and installing Magic Earth using Aurora Store in Shizuku mode.

**Comment by nexx512** [comment]
> I've tried to install LSPosed following the README.md documentation and activate LSPosed android auto extension selecting Magic Earth application and it works. After rebooting the AA shows the map on the application.

I tried this and it actually worked now. However I also installed man other updates in the meantime, so It's hard to tell if the updates Bad an effect in this. But because it is Wirkung now, I will close this issue.
Thanks a lot for all the contributions in this issue.
