### ISSUE TITLE
Google maps disapears after installing

### ISSUE THREAD

**Issue by TheHighGroundWins** [sn-00-x/aa4mg#19]
google maps disappears but appears as in aurora store, both when google maps is already installed and not installed.

**Comment by v1nc** [comment]
You should not install the maps stub if you have maps installed.
1. Uninstall android auto updates
2. Uninstall aa4mg via magisk & reboot
3. Install Maps
4. Install aa4mg again, select "no" if it asks to install maps stub

**Comment by TheHighGroundWins** [comment]
Thanks it works with that method
