### ISSUE TITLE
Android 14 support

### ISSUE THREAD

**Issue by bladeSk** [sn-00-x/aa4mg#20]
Android Auto (10.6.634064) crashes on Android 14 with the current version of aa4mg. I tried this on a Pixel 7 running [CalyxOS 5.0.3 2023-11-02](https://release.calyxinstitute.org/panther-factory-23500030.zip), microG v0.2.29.233013-49. It worked perfectly fine on Android 13, so something must've changed.

I uninstalled and reinstalled everything following the guide from the README, enabled every single permission for AA, got the phone to pair with the car's entertainment system and AA crashed afterwards. Here's a logcat dump of connecting the paired phone to the car. 
[AA14.zip](https://github.com/sn-00-x/aa4mg/files/13309991/AA14.zip)

This line seems suspicious - maybe a new A14 permission? `817 W GH.CrashHandler: 11-09 15:39:47.355 D CAR.SERVICE.LITE : Uncaught exception: java.lang.SecurityException: Requires ADD_TRUSTED_DISPLAY permission to create a trusted virtual display.
1699540787.410 10207  9817  9`

**Comment by sn-00-x** [comment]
Thank you very much for the very helpful log message! I just released a new version containing two new permissions that were introduced in A14. Please test and let me know if it works now.

**Comment by bladeSk** [comment]
Thanks for the quick response. I just tested the new version (uninstalled, restarted, reinstalled AA4MG and AA just in case) and it seems to crash on the same permission error. Attaching the log: [10-11_13-15-54.zip](https://github.com/sn-00-x/aa4mg/files/13319229/10-11_13-15-54.zip)

**Comment by sn-00-x** [comment]
Thanks for testing. Can you please try [https://github.com/sn-00-x/aa4mg/releases/download/v0.6.3-a14-test/aa4mg-v0.6.3-a14-test.zip](the pre-release v0.6.3-a14-test)? It contains a new AndroidAuto stub extracted from a current Pixel image.
Beware: I have no A14 phone with microG currently, so could not test. I think the permissions match, but if I messed up anything, that release may result in a boot loop. So please only try, if you know how to disable a Magisk module (e.g. in a shell with usb debugging or by using a custom recovery). Also, please ensure that you uninstall all updates from Playstore, before updating aa4mg.

**Comment by bladeSk** [comment]
Excellent, there was no boot loop and everything's working with this version. Thanks for your help!
